sourcegraph/terraform-aws-executors

- modules/docker-mirror/main.tf
- modules/executors/main.tf
Fixes https://github.com/sourcegraph/sourcegraph/issues/25094.
> Refactor autoscaling

- .buildkite/check-latest-tag.sh
- .buildkite/pipeline.yaml
- examples/multiple-executors/main.tf
- examples/single-executor/main.tf
Mirrors https://github.com/sourcegraph/terraform-google-executors/pull/21
> Check latest tag

- .buildkite/check-latest-tag.sh
- release.sh
Same as https://github.com/sourcegraph/terraform-google-executors/pull/23
> Add release script

- .buildkite/check-latest-tag.sh
- README.md
- examples/multiple-executors/README.md
- examples/single-executor/README.md
- modules/docker-mirror/README.md
- modules/executors/README.md
- modules/networking/README.md
Same as https://github.com/sourcegraph/terraform-google-executors/pull/24
> Check markdown link versions

- examples/multiple-executors/main.tf
- main.tf
- modules/docker-mirror/main.tf
- modules/docker-mirror/variables.tf
- modules/executors/main.tf
- modules/executors/startup-script.sh.tpl
- modules/executors/variables.tf
Sister PR to https://github.com/sourcegraph/terraform-google-executors/pull/52.
Testing with our k8s AWS runner.
> Add new docker registry node exporter URL variable

- modules/executors/startup-script.sh.tpl
Verified on test cluster that it has access to the registry after these commands.
> Whitelist docker registry IP in network

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/executors/README.md
- modules/networking/README.md
> Prepare release for 3.42.1 module version

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> Prepare for 3.43 release

- modules/docker-mirror/main.tf
- modules/executors/main.tf
This saves one request in case the image has been overwritten.
Verify on k8s cluster where I want to use this.
> Conditionally fetch data source

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/executors/variables.tf
- modules/networking/README.md
> Prepare 4.0.0 release

- modules/executors/startup-script.sh.tpl
Enables https://github.com/sourcegraph/sourcegraph/pull/41912.
Tested on k8s cluster.
> Use native registry feature instead of startup script

- README.md
- RELEASE.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> Prepare 4.2 Release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
Update for 4.4 release (see `RELEASE.md` for details on release process).
No Test needed.
> Update for 4.4.0 release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/executors/README.md
- modules/networking/README.md
Patch release for #64.
No tests needed.
> Update files for 4.4.1 release

- .editorconfig
Not much else to say besides the title
None
> chore: add `.tf` to `.editorconfig`

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/executors/README.md
- modules/networking/README.md
Patch release for docker auth config.
No tests
> Update files for 4.4.2 release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
Update for 4.5.0 release.
No tests
> Update files for 4.5.0 release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> Update files for 5.0.0 release

- examples/multiple-executors/main.tf
terraform fmt CI error fix
n/a
> terraform fmt

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
terraform-aws-executors release
n/a
> Update files for 5.1.0 release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
Part of https://github.com/sourcegraph/sourcegraph/issues/56907
n/a
> Update files for 5.2.0 release

- README.md
> updated README.md links to point to new docsite

- .buildkite/pipeline.yaml
Missed TODO to enable this again
Enabling step in CI pipeline so step should run again
> enable latest tag check - missed todo from previous merge

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> Update files for 5.3.0 release

- .buildkite/pipeline.yaml
> chg/rel: use default sg

- release.yaml
> release: update branch name in release manifest

- modules/executors/variables.tf
This reverts commit 393d106c6f90608976ea33b4a183ef4267d53079.
Commit revert.
> Revert "release: update regex for `ami_version` variable (#102)"

- release.yaml
Remove the hardcoded tag 😮‍💨 
None - this is just removing a hardcoded value
> release: remove hardcoded tag in test

- release.yaml
Testing during next internal release
> release: plug in release registry and change comby logic

- .buildkite/pipeline.yaml
We don't want to run terraform validate and `the latest tag check` on release branches.
> release: update conditional for terraform checks

- .buildkite/pipeline.yaml
> release: update conditional for running tf checks

- release.yaml
* Removing release registry stuff here till we figure out what to do here.
* Uncommenting the finalize steps
> release: update manifest

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
- prepare-release.sh
> Release/prepare 5.8.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
Reverts sourcegraph/terraform-aws-executors#136
> Revert "Release/prepare 5.8.0"

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
- prepare-release.sh
> (internal) release_minor: build v5.8.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
Update tags for 5.9 release
CI
> chore(rel): update tags for 5.9.0 release

- .buildkite/check-latest-tag.sh
- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> chore(rel) update main for v5.11.0

- .buildkite/ci-checkov.sh
- .tool-versions
Update CI tooling versions 
CI
> chore(rel): update CI tooling versions

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/executors/README.md
- modules/networking/README.md
Update tags to latest release 5.11.1
CI
> chore(rel): update tags to latest

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> chore(rel): update for with 6.1.0 release

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.2.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.3.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.5.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.6.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.7.0

- README.md
- examples/multiple-executors/README.md
- examples/multiple-executors/main.tf
- examples/private-single-executor/main.tf
- examples/single-executor/README.md
- examples/single-executor/main.tf
- modules/docker-mirror/README.md
- modules/docker-mirror/main.tf
- modules/executors/README.md
- modules/executors/main.tf
- modules/networking/README.md
> (internal) release_minor: build v6.8.0
